#!/usr/bin/env python
# Copyright 2010 The Board of Trustees of The Leland Stanford Junior University
# SPDX-License-Identifier: Apache-2.0

# This file was derived from code in the Floodlight OFTest repository
# https://github.com/floodlight/oftest released under the OpenFlow
# Software License:
# https://github.com/floodlight/oftest/blob/master/LICENSE
# See file README-oftest.md in the ptf repository for more details.
"""
@package ptf

Packet Test Framework (ptf) top level script.

This script is a thin wrapper around the library. It calls ptf.cli.main().
That function parses the command line, builds a ptf.runner.PtfConfig, and
starts the run through the library (ptf.runner.run). The test-run logic is
in the ptf package. Other programs can call the library directly, without
this script. See the module docstring of ptf.runner.
"""

import os
import sys

root_dir = os.path.dirname(os.path.realpath(__file__))

pydir = os.path.join(root_dir, "src")
if os.path.exists(os.path.join(pydir, "ptf")):
    # Running from source tree
    sys.path.insert(0, pydir)

from ptf.cli import main

if __name__ == "__main__":
    sys.exit(main())
