# SPDX-FileCopyrightText: 2026 The P4 Language Consortium
#
# SPDX-License-Identifier: Apache-2.0

name: Publish Release

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "Version.txt"

permissions:
  contents: write

# Cancel any preceding run on the pull request.
concurrency:
  group: release-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  publish-release:
    if: ${{ github.repository == 'p4lang/ptf' }}
    uses: p4lang/.github/.github/workflows/publish-release.yml@main
    with:
      version_file: Version.txt

  publish-to-pypi:
    name: Publish a Python distribution to PyPI
    if: ${{ github.repository == 'p4lang/ptf' }}
    needs: publish-release
    runs-on: ubuntu-latest
    environment: pypi
    permissions:
      id-token: write
    steps:
    - uses: actions/checkout@v6
    - name: Install uv
      run: ./CI/install-uv.sh
    - name: Build a binary wheel and a source tarball
      run: uv build --out-dir dist/
    - name: Publish distribution to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        skip-existing: true
